all: test add subtract convert pair dlink
test: test.c
	gcc -o test test.c
add: add.c
	gcc -o add add.c
subtract: subtract.c
	gcc -o subtract subtract.c
convert: convert.c
	gcc -o convert convert.c
pair: pair.c
	gcc -o pair pair.c
dlink: dlink.c
	gcc -o dlink dlink.c
